### ISSUE TITLE
Offer option to delete logs after failed run

### ISSUE THREAD

**Issue by ArWeHei** [pesser/edflow#100]
**Is your feature request related to a problem? Please describe.**
When debugging my code I often find myself with half a dozen runs that crash at the very begging yet clutter the logs dir and make it less neat

**Describe the solution you'd like**
After a run crashes due to an error in the code, one should be offered an option to delete the current run logs

**Describe alternatives you've considered**
Delete the logs manually but this is tedious.

**Comment by pesser** [comment]
how should we decide what constitutes a "failed run"? write out the number of steps that were run to filter for runs with number of steps == 0?
i also thought about making the "-n <name>" option exclusive, so if i start training with "-n exp01" and there is already a log folder "logs/<date>-exp01" edflow will ask to overwrite "y / N". that would avoid cluttering the log dir in the first place but also force you to come up with unique names for experiments.

**Comment by pesser** [comment]
running in debug mode `-d` will move the log dir to a `debug_runs` subfolder which avoids cluttering the logdir. After trying different things, I like this solution: Running in debug mode then gives you multiple advantages:
- reduced dataset size to see if bad things happen after an epoch, ie when evaluation starts
- post mortem debugging (`pip install pudb` for the ultimate experience, though not required)
- no log clutter
So my workflow: Debug with `-d` until it runs, then remove the `-d` flag.

(#229 also makes `-d` usable in combination with `-p` to enable better debugging of evaluations for existing projects/models. it then only moves the last eval folder)
