### ISSUE TITLE
Automate and test pypi release

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#119]
For usability it is way more easy to simply `pip install edflow`, but this requires that we regularly upload edflow versions to pypi.

This should be automated, e.g. we could run a script daily/weekly. The alternative of uploading manually seems like a bad choice for me.

**Comment by jhaux** [comment]
@conrad784, maybe you could add this to travis?

**Comment by pesser** [comment]
iirc "the alternative of uploading manually" turned out to be the better choice
