### ISSUE TITLE
Documentation of config paramters

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#123]
It usually is super helpful to comment config parameters. These comments are lost when dumping the config. Also it is not possible to add new parameters to the config on the fly without adding a comment to the dumped config.

This would be possible, I think,  with `ruamel`: https://yaml.readthedocs.io/en/latest/example.html, but would mean, that we have to swap the yaml backend.

If there is interest in this feature, I would love to take a look at it.

**Comment by pesser** [comment]
sounds nice but i think we talked about it and decided it's not worth the hassle: we convert to a plain dictionary and will loose comments at that point regardless of which yaml backend we are using. hence we would need to implement comments ourselves on top of the dictionary. reopen if you see it different.
