### ISSUE TITLE
Add Coverage report badge

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#133]
https://github.com/dwyl/repo-badges

> Test/Code Coverage - codecov.io Code Coverage - coverage is the measure of how much of the code in a project is tested. Anything below 100% coverage means the module/library has potential bugs which are unknown to the authors/users. We avoid using modules with less than 100% coverage and encourage others to question why the authors did not put in the time to test their code... ALL our code is tested. we cannot guarantee every line is "bug-free", (and always welcome people reporting any issues!) however we are meticulous about testing our work and always add regression/edge test cases where bugs are discovered!

**Comment by ArWeHei** [comment]
How about adding a documentation coverage badge as well?
And I would suggest as PyPI badge as well from now on...
...and one of these https://docs.readthedocs.io/en/stable/badges.html

**Comment by ArWeHei** [comment]
https://shields.io/category/coverage, you think this would be sufficient?

**Comment by pesser** [comment]
i see some coverage badge on the readme now. can this be closed?

**Comment by pesser** [comment]
I'll assume yes :)
