### ISSUE TITLE
Require python3 for pip install

### ISSUE THREAD

**Issue by ArWeHei** [pesser/edflow#147]
**Describe the bug**
When installing edflow through pip install with the wrong environment, it will install but not work

**To Reproduce**
1. create default conda env
2. activate env
3. pip install edflow
4. edflow -h throws 'command not found'

**Expected behavior**
pip won't install edflow with incompatible python version

**Additional context**
Also we should add the tensorboardX dependency if it isn't in edflow already

**Comment by pesser** [comment]
didnt add tensorboardX to dependencies because it is only used for pytorch logger.
if we add tensorboardx support to a generic logger (e.g. minimal_logging_hook) it will make sense to add it. but currently i'm trying to reduce our dependencies, which i started in #152

**Comment by theRealSuperMario** [comment]
I agree with @pesser that we should keep dependencies minimal. Tensorboard is now included in the new release of pytorch, so maybe we can kill this dependency after all.
