### ISSUE TITLE
make opencv dependency optional

### ISSUE THREAD

**Issue by pesser** [pesser/edflow#150]
https://github.com/pesser/edflow/blob/e4047d16d23c0c4a341ad95eda552f86676388ce/edflow/data/util.py#L9

this is the only place we are using opencv. its only use is for some optical flow functionality. since opencv is a bit of a heavy dependency, i would prefer to make it optional. both `eval/pipeline.py` and `util.py` import `data.util`, so we have to refactor the optical flow utilities into its own module. i suggest under `applications/`.

assigning the people of which i know they use optical flow - have fun :)

**Comment by conrad784** [comment]
>so we have to refactor the optical flow utilities into its own module. i suggest under `applications/`.
 
util.py only uses cv2 for 
```edflow/data/util.py:import cv2  # noqa
edflow/data/util.py:    mag, ang = cv2.cartToPolar(flow[..., 0], flow[..., 1])
edflow/data/util.py:    hsv[..., 1] = cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX)
edflow/data/util.py:    rgb = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)
```
those functions can be implemented manually, what do you want to move to `applications/`?

**Comment by pesser** [comment]
for example we have `edflow/applications/tf_perceptual_loss.py` which implements the perceptual loss for tensorflow. but no core packages of edflow import this file, so our dependency on tensorflow remains optional. My suggestion is to move every function in `edflow/data/util.py` which provides functionality for optical flow computations (`flow2hsv`, `hsv2rgb`, `flow2rgb` should be all) to `applications/optical_flow.py` and then remove `opencv` as a dependency of edflow. only people who want to use the optical flow module must then install opencv.
