### ISSUE TITLE
Multistage trainer

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#156]
It would be nice to have a Trainer class that supports multiple training stages. For instance a pretraining and then a usual training phase

ideally, it could behave like this

`    Stages are defined through the config. For example

        stages:
          1:
            name: pretrain
            end: 10
            losses: []
          2:
            name: retrain
            end: 30
            losses: ["model"]
          3:
            name: train
            losses: ["model"]

    The stages are sorted by their key. It is recommended to keep the simple numeric ordering.
    In each stage, a set of losses can be specified through the `losses : [ "loss1", "loss2", ...]` syntax.
    The duration of each stage is given by the `end : num_steps` value. Note that the end of a stage
    is determined in the order of the stages. A later stage has to have a higher end value then the previous one.`

**Comment by pesser** [comment]
closed by #157
