### ISSUE TITLE
How to automatically resize input images in template_tfe example

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#158]
**Is your feature request related to a problem? Please describe.**
In the old Iterators before tfe, we could simply use the `spatial_size` key from the config to resize the image. How is that possible in the new iterator?

**Describe the solution you'd like**
I would like to keep the option from the config to simple resize from the config file

**Describe alternatives you've considered**
* resizing everybatch manually in the step ops could be an option but that would mean all the old conveniences are lost.

**Comment by pesser** [comment]
this is not an issue of the new iterator. `spatial_size` is used by quite a few datasets to resize images appropriately. if it doesn't work, it means the dataset does not care to resize.
Quick fix is to add the resizing support to the dataset of interest but maybe we want to move towards more configurable dataset preprocessing chains? Something like

    preprocessing:
        chain:
            - Resize
            - Crop
        Resize:
            spatial_size: 256
        Crop:
            size: 128

**Comment by pesser** [comment]
closing as this is completely dataset dependent. Please create a new issue _if_ you want to develop a generic solution to preprocessing chains
