### ISSUE TITLE
Documentation is not created automatically

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#170]
Currenlty we have to generate the documentation by hand using the following commands:

```
pip install sphinx sphinx_rtd_theme
pip install sphinxcontrib-apidoc

cd <edflow_root>/docs

sphinx-apidoc -o ./source/source_files ../edflow
make html
```

This should be done automatically.

**Comment by pesser** [comment]
why is that? readthedocs used to build the documentation itself, no?

**Comment by ArWeHei** [comment]
I'm on it, should be done by Thursday

**Comment by ArWeHei** [comment]
See #186

**Comment by jhaux** [comment]
Nice job Arthur!!!
