### ISSUE TITLE
Late loading option for datasets

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#171]
When stacking and rearranging datasets it can happen, that a load of data reading is done (e.g. images), which are not used in the end. E.g. making a `SequenceDataset` to get the first and last frame of a temporally connected sequence of images. All intermediate frames need not be loaded.

We could use the template iterator approach to allow `Callables` as example values, which are only evaluated once the example is fed to batching or the model/iterator. This might conflict with the multiprocessing code of the batching.

This should speed up data loading significantly for multiply stacked datasets.

Please let's discuss this Thursday.

**Comment by pesser** [comment]
will be closed by #172
