### ISSUE TITLE
Make plot batch output white background

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#184]
**Is your feature request related to a problem? Please describe.**
plot batch initializes the array with 0 values, however, the image representation in the edflow backend is [-1, 1]. This results in gray unused tiles of the canvase.

Why not just initialize with 1? Then the canvas is white by default. This would look much nicer.

**Describe the solution you'd like**
initialize array with 1.0 https://github.com/pesser/edflow/blob/adffa941d11068af6890ffa09b44f9c7f7d780e9/edflow/iterators/batches.py#L38

**Comment by pesser** [comment]
closed by #195
