### ISSUE TITLE
weights and biases integration

### ISSUE THREAD

**Issue by pesser** [pesser/edflow#219]
I put a minimal wandb logging integration on the [dev-wandb](https://github.com/pesser/edflow/tree/dev-wandb) branch. You can sign up on https://www.wandb.com/, `pip install wandb && wandb init <secret>` as they will tell you, and then run `edflow -b template_pytorch/config.yaml -n testexample --log_to_wandb True -t`. This adds some nice features:
- plots of logged values, even without access to the servers
- status of all runs as running, killed etc. and their configs
- I think they also implement a git integration similar to our own
- you can add notes to the runs
- ...

Unfortunately, it currently messes up the logging output on the console. In fact, you can also see the logging output on their webpage but there it is also messed up. I think this has to do with the tqdm progress bar. I'm not gonna work on it for now, but it would be great if someone else is motivated to do so.

**Comment by jhaux** [comment]
https://docs.wandb.com/library/advanced/environment-variables

```
WANDB_SILENT
Set this to true to silence wandb log statements. If this is set all logs will be written to WANDB_DIR/debug.log
```

**Comment by pesser** [comment]
unfortunately that doesn't fix it. I think we first have to create a minimal example where it fails (seems to be the case whenever we use our `TqdmHandler` for logging).

**Comment by pesser** [comment]
minimal example:
```python
import logging, os, sys, time
from tqdm import trange, tqdm
import wandb
if len(sys.argv) > 1:
    wandb.init()
for i in trange(100):
    time.sleep(0.1)
    tqdm.write("step {}".format(i))
```
Using `file=sys.stderr` in `tqdm.write` fixes it. Not optimal, but also not horrible.
