### ISSUE TITLE
running the example somehow requires torch and tensorboardX

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#23]
with a clean checkout and environement, I need to install torch and tensorboardX to run the mnist_tf example.

even after checking out an older version (e8e96bba2b33ac47cc01aa6e03085d8fe0f109d3)

**Comment by pesser** [comment]
yup, my bad for merging #14. The problem is here: https://github.com/pesser/edflow/blob/4c8400aa16dae4548995c60ceb861db4d72ebf86/edflow/iterators/model_iterator.py#L6 but should be fixed with #20
