### ISSUE TITLE
eval mode does not produce any outputs after completed training

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#232]
**Describe the bug**
Calling `edflow -p <project> -b <project>/configs/<train_config>` Produces no outputs without throwing an error as the condition `Iterator.get_global_step() >= config['num_steps']` is met.

**To Reproduce**
Run an experiment as described above

**Expected behavior**
During evaluation mode, this condition should be never met as we are assuming that there will only be one epoch and we will iterate over the entire data of that epoch.

**Desktop (please complete the following information):**
Experiments we run on the IWR machines with current pesser/master code.

**Comment by pesser** [comment]
should already be fixed on dev branch. Can you confirm?
Do you think we should fix it seperately on master or just try to merge dev as soon as possible?

**Comment by jhaux** [comment]
I cannot yet confirm, but in my opinion we should try to merge into master as soon as possible. The reason being, that the tests would make sense again.

**Comment by pesser** [comment]
definitely fixed in #250
