### ISSUE TITLE
do we need fastnumbers?

### ISSUE THREAD

**Issue by pesser** [pesser/edflow#237]
are we happy without fastnumbers? #235 
@jhaux can you say something? iirc you introduced it in the first place

**Comment by jhaux** [comment]
I would say, for now we are happy without `fastnumbers` as this bug has been encountered by quite a few people (@hperrot , @mritv, Richard). The reason for choosing `fast_int` was that we omit the less efficient `try`-`except` statement (see the image). `fast_int` is roughly 8 times faster but on a timescale of nano seconds. Thus we should try to get `fast_int` working again, but for now not using it is the fine and allows people to use edflow.

![tiimeit](https://user-images.githubusercontent.com/9572598/73599102-28071e00-4540-11ea-9cf9-daf51d403892.png)
