### ISSUE TITLE
Checkpoint at failure suppresses error output

### ISSUE THREAD

**Issue by pesser** [pesser/edflow#24]
This line
https://github.com/pesser/edflow/blob/4c8400aa16dae4548995c60ceb861db4d72ebf86/edflow/hooks/train_hooks.py#L74
causes some problems. Exception due to error in graph gets caught and then we exit silently. Strangely, it actually doesn't exit but just hangs - and we don't get notified about the exception.

Do we need the exit statement here?

**Comment by ArWeHei** [comment]
I think that this also has something to do with the bug I encountered on my local machine:
After starting edflow, I cannot quit the process with keyboardInterrupt although the command line is visible before it is moved due to the output of edflow
