### ISSUE TITLE
Dataset code is cluttered

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#26]
This issue is related to #25 

Navigating the code in ``data.datasets`` is hard as there is a huge amount of functionality.
I would propose that the script should be split into the following subcategories:
- ``dataset_mixin.py``: The base class with documentation
- ``agnostics/``: All datasets, which make no assumptions on the data (e.g. ``ConcatenatedDataset``)
- ``believers/``: All datasets, which make assumptions on the data (e.g. ``SequenceDataset``)
- ``util/``: Data specific utils like ``plot_datum``, which help debugging and interpreting datasets. 

Scripts should probably still be split afterwards to have the folder structure represent the semantic structure in a sense.

For ease of import we should probably import all relevant data structures in the toplevel ``__init__``, i.e. to allow ``from edflow.data import SequenceDataset``.

**Comment by pesser** [comment]
closed by #167
