### ISSUE TITLE
lr_decay_begin and lr_decay_end has to be specified, although not intended

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#3]
https://github.com/pesser/edflow/blob/95d330e94c224921ce109a50147db02def51acaf/edflow/iterators/trainer.py#L236-L237

When I do not want so set lr_decay_begin or end because I do not want lr decay, I still need to provide it otherwise edflow exits

We could just set a default value like

`self.lr_decay_begin = self.config.get("lr_decay_begin", self.num_steps - 1)`

as num steps has to be provided anyway

**Comment by ArWeHei** [comment]
Solved by #
