### ISSUE TITLE
[backwards compatible version] how to only evaluate model 

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#49]
when running
`edflow -e ...` without -t, it gives error that no train option was provided

Only tested in https://github.com/pesser/edflow/commit/c145906128fb2a3828fe2579fe6f99b275a85d80
revision

**Comment by pesser** [comment]
strange, I never encountered this and am running edflow -e all the time. What is causing this? Does it only affect old versions?

**Comment by theRealSuperMario** [comment]
It is caused by a lack of a base config, which in this case would be the -t option.

This probably relates to https://github.com/pesser/edflow/pull/62#discussion_r293022624
