### ISSUE TITLE
hyperparameter expension makro for automating random search

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#50]
something like

learning_rate : random_range(0, 1, 10)

all those expension should be added to a grid eventually and then be executed n a queue

**Comment by pesser** [comment]
We should discuss how to achieve that, i.e. how such a queue would look like.

**Comment by pesser** [comment]
with wandb integration included, I think it would be cool to make [their hyperparameter sweeps feature](https://docs.wandb.com/sweeps/overview) work with edflow.

**Comment by pesser** [comment]
closing here; now tracked in #243
