### ISSUE TITLE
Logging images with tensorboard

### ISSUE THREAD

**Issue by LeanderK** [pesser/edflow#54]
It looks like images are currently saved as pngs and not logged with tensorboard. I need images to be logged with tensorboard because some of my images are not samples, but matplotlib-plots that capture some detailed statistics of my architecture-performance and I therefore would like to keep close track of them during training and compare them in tensorboard.

**Comment by LeanderK** [comment]
maybe a simple change in the constructor ("log_images_to_tensorboard=False") would be sufficient? Then an additional image-save hook could save them to the directory.

**Comment by theRealSuperMario** [comment]
I also thought about a simple switch in the config to allow this.
