### ISSUE TITLE
save actual config file not not log file with config values

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#56]
right now, the actual .yaml file is not saved into the logs folder, but printed into the .log file.
It would be nice to actually save the .yaml file

**Comment by pesser** [comment]
is it not? My configs are saved along with the code in the `code` subfolder!?

**Comment by theRealSuperMario** [comment]
* the running config should be saved somewhere else and not just within the code/sub/sub/folder
* the train/log.txt prints the config very ugly
`{'grad_weight': {'end': 20000, 'end_value': 1e-06, 'start_value': 1e-06, 'start': 10000}, 'data_avoid_identity': False, 'lr_decay_begin': 250000, 'final_hour': {'extra_resnets': 0, 'activation': 'leaky_relu', 'upsample_method': 'subpixel', 'config': [32, 64]}, 'data_root': 'data/deepfashion', 'data_flip': True, 'local_app_size': 128, 'encoder1': {'extra_resnets': 4, 'activation': 'leaky_relu', 'config': [32, 64, 128, 128, 256, 256, 256]}, 'discriminator': {'activation': 'leaky_relu'}, 'dv': {'activation': 'leaky_relu', 'upsample_method': 'subpixel', 'config': [16, 32, 32, 128, 128, 256, 256]}, 'apply_softmax': False, 'd_debug_mask': {'extra_resnets': 0, 'activation': 'leaky_relu', 'upsample_method': 'conv_transposed', 'config': [32, 64]}, 'MI': {'loa_adaptive': True, 'mi_slack': 0.05, 'mi_target': 0.2, 'lor_max': 7.5, 'loa_lr': 4.0, 'lor_adaptive': True, 'lor_min': 0.0, 'loa_init': 0.0, 'lor_lr': 0.05, 'lor_init': 0.0}, 'ckpt_freq': 5000, 'batch_size': 4, 'data_csv': 'data/deepfashion/filtered_train.csv', 'encoder0': {'extra_resnets': 4, 'activation': 'leaky_relu', 'config': [32, 64, 128, 128, 256, 256, 256]}, 'model': 'nips19.SB_model30b.model.TrainModel', 'dv_upsample': 1, 'localization_weight': {'end': 10000, 'end_value': 1e-11, 'start_value': 1e-11, 'start': 5000}, 'restore_exclude': ['pretty_discriminator', 'beta1_power_7', 'beta2_power_7', 'phase_weight', 'grad_weight', 'beta1_power_8', 'beta2_power_8', 'phase_gamma', 'gumbel_temp'], 'triplet_path': 'triplet_checkpoints/deepfashion/triplet_reid.ckpt-99000', 'kl_weight': {'end': 1, 'end_value': 1.0, 'start_value': 1.0, 'start': 0}, 'gumbel_temp': {'step_size': 5000, 'stair_factor': 0.9, 'start_value': 1.0, 'start': 25000}, 'pretrain': True, 'spatial_size': 256, 'd_mean_beta': {'activation': 'leaky_relu', 'upsample_method': 'conv_transposed', 'config': [8, 8, 8, 8, 8, 8, 8]}, 'lr_decay_end': 500000, 'n_parts': 10, 'num_steps': 100001, 'dataset': 'nips19.data.data.StochasticPairs', 'log_freq': 250, 'iterator': 'nips19.SB_model30b.model.Trainer', 'lr': 0.0002, 'z0_size': 256}`
* the top level log.txt will be overwritten when resuming training with -p or evaluationg with -p
