### ISSUE TITLE
assumes src files to be within directory

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#59]
For example this works:

foo/model.py
foo/data.py

`
model: foo.model.Model
dataset: foo.data.Dataset
`
run edflow from above foo

But this does not work

foo/model.py
foo/data.py

`
model: model.Model
dataset: data.Dataset
`
run edflow from within foo

**Comment by pesser** [comment]
yes this is the heuristic we use here
https://github.com/pesser/edflow/blob/c6c73efa581fa1032ce7a02387c471483648de98/edflow/edflow#L60-L69

what would you like to happen?

**Comment by theRealSuperMario** [comment]
I intended this to be more like a note that should be moved to the docs.
