### ISSUE TITLE
use less GPU memory for inference

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#63]
use less gpu memory for inference when using -e only.

This should be possible. right now, the whole gpu is used

**Comment by pesser** [comment]
the tf iterator has support for `nogpu`, `gpu_mem_growth` and `gpu_mem_fraction` https://github.com/pesser/edflow/blob/c6c73efa581fa1032ce7a02387c471483648de98/edflow/iterators/tf_iterator.py#L184-L191

they can simply be specified in the eval config. do we need to keep this open?
