### ISSUE TITLE
travis runs twice

### ISSUE THREAD

**Issue by pesser** [pesser/edflow#69]
when pushing a branch to this repo and then making a pull request to master, travis runs the test twice. Can this be fixed in travis? Maybe we should run travis tests only for PRs?

**Comment by theRealSuperMario** [comment]
while we are fixing our test hooks, we can rewrite the test runs so that we run a test matrix. this will be run in parallel. right now we have a sequential test pipeline. If a single test within the pipeline fails, it is completely halted.

**Comment by pesser** [comment]
only pull requests are tested now
