### ISSUE TITLE
CachedDataset behaving weirdly

### ISSUE THREAD

**Issue by ArWeHei** [pesser/edflow#73]
I made this observation a few times now and also on different machines.
Whenever I want to start a worker with edcache the worker will initially not start properly stating that DataToCache argument is not given. BUT if I ever started edflow with DataToCache as dataset before running edcache it magically works w/o any problems

**Comment by ArWeHei** [comment]
I suspect, that the class requires a cached dataset in the data directory, that makes actual remote data mining a bit difficult. It works with this trick but ultimately it would be nice to send the config to the client

**Comment by ArWeHei** [comment]
Also, the zip file not closed correctly if the server is interrupted and results in the server not being able to open the zip file. It is possible to repair the file but maybe it would be a better idea to loose the zip file altogether

**Comment by pesser** [comment]
yes the whole dataset caching pipeline needs to be reworked. putting things in a zip file in the first place is not a good idea because this becomes really slow when the dataset is large. we should discuss how to proceed with this.

**Comment by pesser** [comment]
edcache should be re-written to use metadatasets. tracked in #201 so I'm closing here
