### ISSUE TITLE
pyproject.toml prevents editable mode

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#79]
running
`pip install -e .`

gives

>  editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

Instead, one can use
`pip install -e . --no-use-pep517 `

**Comment by pesser** [comment]
pep517 seems to have caused quite a bit of trouble there, but i think this was fixed already in `pip >= 19.1.1` (https://discuss.python.org/t/pip-19-1-and-installing-in-editable-mode-with-pyproject-toml/1553/64)
