### ISSUE TITLE
Document how to run tests locally and maybe add a script for that

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#89]
Before creating a pull request it might help to run the tests run by travis locally. Otherwise you put all the work into you pull request, just to find out that you waited 10 long minutes for travis to finish to realize, you had a typo.

This is not hard to do, once you know how, but should be documented. Maybe on could also add some developer tools, which could supply a test script.

**Comment by theRealSuperMario** [comment]
`source activate edflow; pytest --ignore="examples"` from project folder
