### ISSUE TITLE
Evaluator crashes on remote I/O Error

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#92]
**Describe the bug**

I run a training and an evaluator on a different node in parallel. At some point during the training, the evaluator crashed. The training has continued.

  File "/net/hcihome/storage/sabraun/code/edflow_stable/edflow/hooks/checkpoint_hooks/common.py", line 35, in get_latest_checkpoint
    all_files = sorted(os.listdir(ckpt_root))
OSError: [Errno 121] Remote I/O error: 'logs/2019-07-01T17:49:45_coords_1_pretrain_deepfashion/train/checkpoints'

**To Reproduce**
Not sure if this can be reproduced deterministically.

**Expected behavior**
I expect the evaluator to just keep running after all.

**Comment by pesser** [comment]
i don't see what we could do about this. seems to be an issue of the system. feel free to reopen if you disagree.
